System["register"]("chunks:///_virtual/TipsWindows4.ts",["./rollupPluginModLoBabelHelpers.js","cc","./Interlocking_GameData.ts","./Interlocking_AudioManager.ts"],function(t){var n,i,e,r,s,u,a,c,l,f,h,v,w,g,z,B,y,L,d,C;return{setters:[function(t){n=t["inheritsLoose"]},function(t){var n=o;i=t["cclegacy"],e=t["_decorator"],r=t["Color"],s=t.v3,u=t["BlockInputEvents"],a=t["find"],c=t["tween"],l=t["Sprite"],f=t["Widget"],h=t.Node,v=t["UITransform"],w=t["Graphics"],g=t.UIOpacity,z=t["view"],B=t["Canvas"],y=t["Component"]},function(t){L=t["ViewSize"]},function(t){d=t["Interlocking_AudioManager"],C=t.Interlocking_SoundName}],execute:function(){var D,m=o;i["_RF"]["push"]({},"26e56eCprFO4LXGSQEFgzwt","TipsWindows",void 0);var M=e["ccclass"],x=(e["property"],"FullScreenMask"),b=new r(0,0,0,180);t("TipsWindows",M("Interlocking_TipsWindows")(D=function(t){function i(){for(var n,i=o,e=arguments.length,r=Array(e),s=0;s<e;s++)r[s]=arguments[s];return(n=t.call["apply"](t,[this]["concat"](r))||this).maskNode=null,n["maskGraphics"]=null,n["maskOpacity"]=null,n["maskDrawKey"]="",n["succeedCallback"]=null,n["cancelCallback"]=null,n["isCloseIng"]=!1,n}n(i,t);var e=i.prototype;return e["onLoad"]=function(){this["node"]["scale"]=s(0,0,0),this["initFullScreenMask"]();var t=this["node"]["getComponent"](u);t||(t=this["node"]["addComponent"](u));var n=a("button-08",this.node);n&&(n["getComponent"](u)||n["addComponent"](u)),c(this["node"]).to(.8,{scale:s(1,1,1)},{easing:"elasticOut"}).start(),this["syncMaskToScreen"]()},
e.update=function(){this["syncMaskToScreen"]()},
e["start"]=function(){},
e["onClick"]=function(t,n){this["isCloseIng"]||(1==n?this.succeedCallback&&this["succeedCallback"]():2==n&&this.cancelCallback&&this["cancelCallback"](),this["succeedCallback"]=null,this["cancelCallback"]=null,this["close"](),d.GetInstance().playSound(C["click"]))},
e.close=function(){var t=this;this["isCloseIng"]||(this.isCloseIng=!0,c(this.node).to(.3,{position:s(2*L["width"],0,0)},{easing:"cubicIn"}).call(function(){t["node"].destroy()})["start"]())},
e["initFullScreenMask"]=function(){var t=this.node.getComponent(l);t&&(t["enabled"]=!1);var n=this.node["getComponent"](f);n&&(n["enabled"]=!1);var i=this.node.getChildByName(x);i||((i=new h(x))["layer"]=this["node"]["layer"],i.parent=this["node"],i.setSiblingIndex(0)),this["maskNode"]=i;var e=i.getComponent(f);e&&(e["enabled"]=!1);var r=i["getComponent"](v);r||(r=i["addComponent"](v)),r.setAnchorPoint(.5,.5);var s=i["getComponent"](l);s&&(s["enabled"]=!1,s["destroy"]());var o=i["getComponent"](w);o||(o=i["addComponent"](w)),o["fillColor"]=b,this.maskGraphics=o;var a=i.getComponent(g);a||(a=i["addComponent"](g)),this["maskOpacity"]=a,i["getComponent"](u)||i["addComponent"](u),this["syncMaskToScreen"]()},
e["syncMaskToScreen"]=function(){var t=this["maskNode"];if(t&&t["isValid"]){var n=this["node"]["scale"].x,i=this["node"].scale.y;if(.001>Math.abs(n)||.001>Math["abs"](i))this.maskOpacity&&(this["maskOpacity"]["opacity"]=0);else{this["maskOpacity"]&&(this.maskOpacity["opacity"]=255),t["setScale"](1/n,1/i,1);var e=z["getVisibleSize"](),r=Math["max"](e["width"],e["height"],2),o=e.width+r,u=e["height"]+r,a=t["getComponent"](v);a||(a=t["addComponent"](v)),a["setContentSize"](o,u),this["redrawMask"](o,u);var c=this["findCanvasNode"](),l=c&&c["getComponent"](v),f=this.node["getComponent"](v);if(l&&f){var h=l["convertToWorldSpaceAR"](s(0,0,0));t.setPosition(f.convertToNodeSpaceAR(h))}}}},
e["redrawMask"]=function(t,n){var i=this.maskGraphics;if(i&&i.isValid){var e=t+"x"+n;this["maskDrawKey"]!==e&&(this.maskDrawKey=e,i["clear"](),i["rect"](-t/2,-n/2,t,n),i["fill"]())}},
e.findCanvasNode=function(){for(var t=this.node;t;){if(t["getComponent"](B))return t;t=t["parent"]}return this["node"].parent},i}(y))||D),i["_RF"].pop()}}});
